### ISSUE TITLE
將每個 API 加上 swagger 文件

### ISSUE THREAD

**Issue by typingmonk** [ronnywang/pcc.g0v.ronny.tw#6]
As title.
增加 swagger 文件

**Comment by typingmonk** [comment]
To @ronnywang :

在 `api/searchbycompanyid`, `api/searchbycompanyname`, `api/searchbytitle` 這三隻 API 中
如果有在 GET request 中給 `columns` 的值，`records` 中每一個查到的標案會多一個 key 叫 `detail`
試了幾個值都只得到 `detail: []`，這個原本是希望能多查到哪些資訊？希望給一個 `columns` 的 URL 範例

https://github.com/openfunltd/pcc.g0v.ronny.tw/blob/5dc072e86d39f9b6250577f6bceb67d38f03eb98/webdata/controllers/ApiController.php#L337-L343

**Comment by typingmonk** [comment]
在 `api/tender` 中可以看到 `datail` 的資料呈現方式：

```json
"detail": {
  "type": "公告類型",
  "url": "https://web.pcc.gov.tw/prkms/tender/",
  "機關資料:機關代碼": "3.79",
  "機關資料:機關名稱": "臺北市政府",
  "fetched_at": "2017-08-28T15:03:43+08:00"
}
```

https://github.com/openfunltd/pcc.g0v.ronny.tw/blob/5dc072e86d39f9b6250577f6bceb67d38f03eb98/webdata/controllers/ApiController.php#L426-L429

**Comment by ronnywang** [comment]
> To @ronnywang :
> 
> 在 `api/searchbycompanyid`, `api/searchbycompanyname`, `api/searchbytitle` 這三隻 API 中 如果有在 GET request 中給 `columns` 的值，`records` 中每一個查到的標案會多一個 key 叫 `detail` 試了幾個值都只得到 `detail: []`，這個原本是希望能多查到哪些資訊？希望給一個 `columns` 的 URL 範例
> 
> https://github.com/openfunltd/pcc.g0v.ronny.tw/blob/5dc072e86d39f9b6250577f6bceb67d38f03eb98/webdata/controllers/ApiController.php#L337-L343

https://pcc.g0v.ronny.tw/api/searchbycompanyid?query=22555003&page=1&columns[]=%E5%B7%B2%E5%85%AC%E5%91%8A%E8%B3%87%E6%96%99:%E6%A8%99%E6%A1%88%E5%90%8D%E7%A8%B1
上面是範例，後面可以用 columns[] 指定想要多傳哪些欄位，而欄位的部份可以看 https://openfunltd.github.io/pcc-viewer/tender.html?unit_id=3.97.5.56&job_number=Tyjh-2023-16&date=20230908&filename=BDM-1-70378259 左邊的欄位都可以使用
