### ISSUE TITLE
/api/searchbycompanyid 會跳出 http status 500

### ISSUE THREAD

**Issue by typingmonk** [ronnywang/pcc.g0v.ronny.tw#7]
Production 上的 `/api/searchbycompanyid` 沒有問題 https://pcc.g0v.ronny.tw/api/searchbycompanyid?query=24935439
但用 master 上的程式碼時會因為型別問題出錯
#### errorlog: 
```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: stdClass / int in webdata/controllers/ApiController.php:106
Stack trace:
#0 work/pcc/webdata/stdlibs/pixframework/Pix/Controller.php(264): ApiController->searchbycompanyidAction()
#1 work/pcc/index.php(20): Pix_Controller::dispatch()
#2 {main}\n  thrown in work/pcc/webdata/controllers/ApiController.php on line 106
```

#### How to fix

照其他 api endpoint 算 `total_pages` 的邏輯，把 `$ret->hits->total` 改成 `$ret->hits->total->value`
https://github.com/openfunltd/pcc.g0v.ronny.tw/blob/5dc072e86d39f9b6250577f6bceb67d38f03eb98/webdata/controllers/ApiController.php#L106

**Comment by ronnywang** [comment]
嗯，elastic 7.0 之後把 hits->total 的格式改掉了（為了支援「大於10000筆」這種回傳格式）
而標案資料最早開發時是 elastic 2.4.3 ，我在今年八月才更新到 elastic 8.8.2 ，有些地方忘了改

這邊就麻煩你幫我改囉

**Comment by typingmonk** [comment]
Merge commit: https://github.com/openfunltd/pcc.g0v.ronny.tw/commit/780ea220b5a2e25580d9c746f0f348668fe3fbf6
